kind: Service
apiVersion: v1
metadata:
  name: bluegreenlb
  labels:
    app: bluegreenlb
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: blue
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: samhmariam/capstone:v1
        ports:
        - containerPort: 80